### ISSUE TITLE
Occasional BAD_EXEC_ACCESS on 	[readStream open];

### ISSUE THREAD

**Issue by jeeftor** [albertodebortoli/GoldRaccoon#4] opened 2014-01-24 15:48 UTC
So i actually ended up here because I was using Black Raccoon and was having issues (I'm glad i switched over though because I like the gold architecture better).  In any case I've been having intermittent issues with line 74 of GRStreamInfo.m

I'm looping through a table and creating temp files on the disk then I loop through and send out each file.  With some level of frequency I get a EXEC_BAD_ACCESS call on the line: 

[readStream open];

in the code block:

 readStream.delegate = request;
    [readStream scheduleInRunLoop:[NSRunLoop currentRunLoop] forMode:NSDefaultRunLoopMode];
    [readStream open];

I really am at a loss.  Any ideas?

**Comment by jeeftor** [comment] 2014-01-24 21:30
Is there anything else I can provide to help figure this out?

**Comment by albertodebortoli** [comment] 2014-01-25 22:45
Hi @jlss I never experienced that even with a considerable amount of requests. Next chance I get, I'll try to reproduce the crash.

**Comment by jeeftor** [comment] 2014-01-26 00:23
I'm convinced there is something sketchy in my code I just can't seem to figure it out.  Thanks for giving it a look-see

**Comment by albertodebortoli** [comment] 2014-02-03 22:35
Hey @jiss I tried to run some functional tests and I received that crash just once. I didn't have useful breakpoints to catch exceptions enabled and therefore I wasn't able to debug. Anyway, I refactored a little and I just pushed some minor changes. You might want to try the latest version, who knows...

**Comment by qiuxinyidian** [comment] 2014-05-16 03:52
i use the lasted version  and  get a EXEC_BAD_ACCESS call on the line. .Even i put the codes in @try{} @catch{} @finally{},  i  receive that crash ,app crashes .the exception deal does not work

**Comment by albertodebortoli** [comment] 2014-05-18 00:11
EXC_BAD_ACCESS is due to an internal crash, no exceptions are thrown, so no, you can't try to catch something that is not thrown.

**Comment by animeshsen** [comment] 2014-06-19 19:34
Facing the same EXC_BAD_ACCESS during uploading and app gets crashed.

**Comment by jeeftor** [comment] 2014-06-20 02:51
I'm starting to think this is an apple issue. I've tried every FTP library out there and always run into similar crashes.

**Comment by qiuxinyidian** [comment] 2014-06-27 07:37
to solve this problem,I change ftp to ASIHttpRequest

在 2014年6月20日，上午10:51，jlss notifications@github.com 写道：

> I'm starting to think this is an apple issue. I've tried every FTP library out there and always run into similar crashes. 
> 
> Sent from my iPhone 
>

**Comment by albertodebortoli** [comment] 2014-08-01 10:26
The obsolete ASIHTTPRequest hasn't support for FTP. As the name suggests.

**Comment by albertodebortoli** [comment] 2014-08-01 22:41
Fixed with #15. Many thanks to @t-oginogin!

**Closed as completed** 2014-08-01 22:42 UTC
